[versions]

[libraries]
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.13" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.10.2" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.22" }
microsoft-iot-client = { group = "com.microsoft.azure.sdk.iot", name = "iot-device-client", version = "2.5.0" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.17" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "14.0.1" }
